# Generated by Django 2.2.16 on 2021-11-21 13:40

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211121_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[reviews.validators.my_year_validator], verbose_name='Год выпуска'),
        ),
    ]
